/**
 * swap-offer router
 */

import { factories } from '@strapi/strapi';

export default {
  // We will define routes manually for more control, 
  // but can start with a base core router configuration if needed and then extend/override.
  // For this case, let's define them explicitly.

  routes: [
    // Core routes that we want to keep (optional, can be generated by createCoreRouter and then customized)
    {
      method: 'GET',
      path: '/swap-offers',
      handler: 'swap-offer.find',
      config: {
        // auth: { scope: ['find'] } // Example: ensure this matches a permission
      }
    },
    {
      method: 'GET',
      path: '/swap-offers/:id',
      handler: 'swap-offer.findOne',
      config: {
        // auth: { scope: ['findOne'] }
      }
    },
    {
      method: 'POST',
      path: '/swap-offers',
      handler: 'swap-offer.create',
      config: {
        // auth: { scope: ['create'] }
      }
    },
    // We are not using the generic update for swap-offers directly for status changes.
    // {
    //   method: 'PUT',
    //   path: '/swap-offers/:id',
    //   handler: 'swap-offer.update',
    //   config: {
    //     // auth: { scope: ['update'] }
    //   }
    // },
    {
      method: 'DELETE',
      path: '/swap-offers/:id',
      handler: 'swap-offer.delete',
      config: {
        // auth: { scope: ['delete'] }
      }
    },
    // Custom route for updating status
    {
      method: 'PUT',
      path: '/swap-offers/:id/status',
      handler: 'swap-offer.updateStatus',
      config: {
        // policies: ['global::is-authenticated'], // Example if you have such a policy
        auth: {
            // Ensure this scope is configured in user-permissions roles if using Strapi's RBAC for it
            // For now, controller logic handles auth checks, but API token permissions / RBAC would use this.
        },
        description: 'Update the status of a swap offer (accept, decline, cancel).',
        // tags: [{ name: 'SwapOffer', description: 'Endpoints for managing swap offers' }] // OpenAPI docs tag
      }
    }
  ]
};
